grep "\.latch\|\.subckt\|\.names" agilex.16x16_from_4x4.fp16.fpga_with_dsp/latest/*/*/*/*odin*blif | wc -l
grep "\.latch\|\.subckt\|\.names" agilex.16x16_from_8x8.int8.fpga_with_dsp/latest/*/*/*/*odin*blif | wc -l
grep "\.latch\|\.subckt\|\.names" agilex.arm_core.fpga_with_dsp/latest/*/*/*/*odin*blif | wc -l
grep "\.latch\|\.subckt\|\.names" agilex.bgm.fpga_with_dsp/latest/*/*/*/*odin*blif | wc -l
grep "\.latch\|\.subckt\|\.names" agilex.diffeq1.fpga_with_dsp/latest/*/*/*/*odin*blif | wc -l
grep "\.latch\|\.subckt\|\.names" agilex.LU32PEEng.fpga_with_dsp/latest/*/*/*/*odin*blif | wc -l
grep "\.latch\|\.subckt\|\.names" agilex.mcml.fpga_with_dsp/latest/*/*/*/*odin*blif | wc -l
grep "\.latch\|\.subckt\|\.names" agilex.stereovision0.fpga_with_dsp/latest/*/*/*/*odin*blif | wc -l
grep "\.latch\|\.subckt\|\.names" agilex.stereovision1.fpga_with_dsp/latest/*/*/*/*odin*blif | wc -l
grep "\.latch\|\.subckt\|\.names" agilex.tpu_16x16.int8.fpga_with_dsp/latest/*/*/*/*odin*blif | wc -l
