grep "\.latch\|\.subckt\|\.names" agilex.tpu_32x32.int8.fpga_with_dsp/latest/*/*/*/*odin*blif | wc -l
grep "\.latch\|\.subckt\|\.names" agilex.14x16_from_8x8.int8.fpga_with_dsp/latest/*/*/*/*odin*blif | wc -l
grep "\.latch\|\.subckt\|\.names" agilex.20x20_from_4x4.fp16.fpga_with_dsp/latest/*/*/*/*odin*blif | wc -l
grep "\.latch\|\.subckt\|\.names" agilex.eltwise_add.fpga_with_dsp/latest/*/*/*/*odin*blif | wc -l
grep "\.latch\|\.subckt\|\.names" agilex.eltwise_mul.fpga_with_dsp/latest/*/*/*/*odin*blif | wc -l
grep "\.latch\|\.subckt\|\.names" agilex.arm_core.fpga_with_dsp/latest/*/*/*/*odin*blif | wc -l
grep "\.latch\|\.subckt\|\.names" agilex.bgm.fpga_with_dsp/latest/*/*/*/*odin*blif | wc -l
grep "\.latch\|\.subckt\|\.names" agilex.diffeq1.fpga_with_dsp/latest/*/*/*/*odin*blif | wc -l
grep "\.latch\|\.subckt\|\.names" agilex.LU32PEEng.fpga_with_dsp/latest/*/*/*/*odin*blif | wc -l
grep "\.latch\|\.subckt\|\.names" agilex.LU8PEEng.fpga_with_dsp/latest/*/*/*/*odin*blif | wc -l
grep "\.latch\|\.subckt\|\.names" agilex.mcml.fpga_with_dsp/latest/*/*/*/*odin*blif | wc -l
grep "\.latch\|\.subckt\|\.names" agilex.stereovision0.fpga_with_dsp/latest/*/*/*/*odin*blif | wc -l
grep "\.latch\|\.subckt\|\.names" agilex.stereovision1.fpga_with_dsp/latest/*/*/*/*odin*blif | wc -l
grep "\.latch\|\.subckt\|\.names" agilex.stereovision2.fpga_with_dsp/latest/*/*/*/*odin*blif | wc -l
grep "\.latch\|\.subckt\|\.names" agilex.conv.fpga_with_dsp/latest/*/*/*/*odin*blif | wc -l
